### ISSUE TITLE
Access to client nodes

### ISSUE THREAD

**Issue by pmoc2001** [synhershko/elasticsearch-cloud-deploy#17]
Great work and will support where I can.

Just wondering how you envisioned access to the private subnet. Running the production variant provides an internal DNS such as internal-domain-es-client-lb-248273487.eu-west-2.elb.amazonaws.com  . However, I did notice a kibana public security group.

I just wondering if you planned to use a bastion host or some other VPN method to access cluster for administration and Kibana on port 8080
Regards,

pmoc

**Comment by synhershko** [comment]
VPN :)

The Kibana public security group exists because some of my clients do not have VPN set up. So we allow them to expose the client nodes to the public web, but have X-Pack Security installed or enabled or at the very least use the nginx front to password protect traffic over HTTPS.

HTH
