### ISSUE TITLE
Red cluster after deployment

### ISSUE THREAD

**Issue by philippefuentes** [synhershko/elasticsearch-cloud-deploy#18]
I'm trying to settup the cluster in the default single node mode, after completion, I go to Kibana:
`
http://<MY-EC2-IP>:8080
`
I have a red cluster with the following:

![image](https://user-images.githubusercontent.com/18396482/30338028-167d3cb8-97e2-11e7-9255-1bdc3ef9cba2.png)

Can you tell me what I'm missing ?

Thanks a lot

**Comment by synhershko** [comment]
Elasticsearch isn't running - you will need to log in to the machine and check why that is.

Probably fixed in https://github.com/synhershko/elasticsearch-cloud-deploy/commit/fb4d16037ba08832bd7c320d70f5438f2b27fbf8 tho (recent ES versions broke the installation script we use)
