### ISSUE TITLE
No data nodes running

### ISSUE THREAD

**Issue by andrei-dascalu** [synhershko/elasticsearch-cloud-deploy#23]
I may be a bit of a n00b but I'm facing a strange issue.

I've modified the variables to run a configuration involving 3 master nodes, 3 data and 1 client. Doing plan and apply goes smoothly and all items are created but ...

I have no data nodes running, despite autoscaling group and launch configurations for data nodes being there. 1 client node is running, 3 masters are running but no data nodes are created and I have no errors or anything like it.

I'm wondering if someone has faced this situation before?

**Comment by synhershko** [comment]
I assume you are using the AWS terraforming code. I'm afraid you have provided no helpful information here so I can't really help you here.

**Comment by synhershko** [comment]
This was probably be fixed by either https://github.com/synhershko/elasticsearch-cloud-deploy/commit/ff3c6d8a69eae1ef7177d921c9ca18a5911ad266 or https://github.com/synhershko/elasticsearch-cloud-deploy/commit/62787b8094f79e81e024005f7c87295333986075 or both, closing
