### ISSUE TITLE
Cannot get through nginx auth

### ISSUE THREAD

**Issue by cdimitroulas** [synhershko/elasticsearch-cloud-deploy#40]
When I ran the default single-node setup in AWS, I was unable to authenticate through nginx with the user/password written in the README which was `exampleuser`/`changeme`.

I also tried using the randomly generated password which is outputted at the end of the `terraform apply` command but that also did not work.

Not being particularly familiar with nginx, it was rather annoying to run into this issue. I think this is a great repository which will be useful to a lot of people but if it worked out of the box and the documentation was accurate this would make it much more accessible :)

I had to create a new user/password in order to get access in the end.

**Comment by synhershko** [comment]
Username is `exampleuser` (or whatever other username you set in variables.tf), and the password is now autogenerated when deploying instead of `changeme`. Run `terraform output` after deploying and you should see the password printed out.

**Comment by japel** [comment]
would be nice if the docs were updated... I also run into this issue :(
