### ISSUE TITLE
Required plugin discovery-ec2 not installed on single-node setup (AWS)

### ISSUE THREAD

**Issue by cdimitroulas** [synhershko/elasticsearch-cloud-deploy#41]
It seems that the `discovery-ec2` plugin is required [here](https://github.com/synhershko/elasticsearch-cloud-deploy/blob/875dc2872b1660a68dd385c47f20c2da49a99a84/templates/user_data.sh#L27)

Which I assume is fine for the multi-node elasticsearch cluster (I have not tried this yet), however, in the single-node deployment on AWS the instance is ran with the kibana AMI and the plugin is not installed which causes an error when the `elasticsearch` service runs on the instance.

I would make a PR but I'm not sure what the correct approach is here, should the plugin be installed on the kibana AMI as well? Happy to implement this if that is the case - otherwise I might need some advice.

**Comment by synhershko** [comment]
The Kibana AMI should be based on the Elasticsearch AMI - so that plugin should already be installed?

**Comment by cdimitroulas** [comment]
That doesn't seem to be the case as I had an error saying the plugin was not installed

**Comment by synhershko** [comment]
The Kibana AMI is based on the ES AMI: https://github.com/synhershko/elasticsearch-cloud-deploy/blob/ac76ce59fdab25704ea2ba48cb20a4ed550be957/packer/kibana6-node.packer.json#L18

On the ES AMI we execute the discovery-ec2 install:
https://github.com/synhershko/elasticsearch-cloud-deploy/blob/master/packer/elasticsearch6-node.packer.json#L86
https://github.com/synhershko/elasticsearch-cloud-deploy/blob/master/packer/install-cloud-plugin.sh#L9

If you had a different experience please send more details, after you've made sure you followed the README
