### ISSUE TITLE
Kibana reported that ES is not working in EC2

### ISSUE THREAD

**Issue by tomerleib** [synhershko/elasticsearch-cloud-deploy#44]
Hi,
I've deployed the TF in my AWS environment and when I logged in to Kibana I found out that ES and Logstash is not working at all.

plugin:elasticsearch@6.3.1 - Service Unavailable
plugin:logstash@6.3.1 - Elasticsearch cluster did not respond with license information

I also get multiple errors on x-pack services with the same errors on license information.

I've tested out the network from the coordinated node (aka client) to the masters and also to the data and verified that I was able to reach to ports 9300 and 9200.
What else is needed to check in order to get it working?
![screenshot from 2018-07-08 19-07-30](https://user-images.githubusercontent.com/23291199/42422249-260885f8-82eb-11e8-854b-190c9f97c74d.png)

**Comment by neubineshkuttan** [comment]
How this you fixed this issue?
