### ISSUE TITLE
Error: spot_price should be set to auto when spot_price_auto_product is specified

### ISSUE THREAD

**Issue by bruun** [synhershko/elasticsearch-cloud-deploy#45]
When running `packer build -only=amazon-ebs -var-file=variables.json elasticsearch6-node.packer.json`

**Comment by synhershko** [comment]
Thanks for reporting, can you send a PR fixing that?

**Comment by bruun** [comment]
Sure, just need to find which way to fix it. Just adding `"spot_price": "auto"` to the config produces another error:
 
>Spot instances do not support modification, which is required when either `ena_support` or `sriov_support` are set. Please ensure you use an AMI that already has either SR-IOV or ENA enabled.

So two solutions: Use on-demand over spot instances, or remove the ENA requirement.

**Comment by synhershko** [comment]
Fixed via https://github.com/synhershko/elasticsearch-cloud-deploy/commit/f885f4e706013043e93a488df216f5e72db4c3c3
