### ISSUE TITLE
Need to specify image_publisher, image_offer and image_sku

### ISSUE THREAD

**Issue by adiep-cdpq** [synhershko/elasticsearch-cloud-deploy#58]
When running `packer build -only=azure-arm -var-file=variables.json kibana6-node.packer`, I get this error. 

3 error(s) occurred:

* An image_publisher must be specified
* An image_offer must be specified
* An image_sku must be specified

**Comment by synhershko** [comment]
Have you built the Elasticsearch image before running this command? What version of Packer are you using?

**Comment by adiep-cdpq** [comment]
Yes, I did. I'm using packer version 1.2.5. I ended up having to add 
`"image_publisher": "Canonical",
      "image_offer": "UbuntuServer",
      "image_sku": "16.04-LTS",`
to kibana6-node.packer.json so the command could run properly.

**Comment by adiep-cdpq** [comment]
Ok for some reasons, I succeeded in building the image this morning without the lines I mentionned above. I'm closing this issue.
