### ISSUE TITLE
Kibana deployed with no config?

### ISSUE THREAD

**Issue by michaelseto** [synhershko/elasticsearch-cloud-deploy#64]
Did the terraform apply and out of the box I receive a “Kibana server is not ready”. I ssh and check kibana.yml and everything is commented out

**Comment by synhershko** [comment]
The "Kibana server is not ready" message is completely normal - Kibana takes a while to load on first launch. It should have resolved itself after a few minutes. If not, please reopen and paste the kibana.yml contents and `/var/log/user-data.log`
